name: switchboard
description: Microservice communication protocol layers.  
version: 2.0.8
homepage: https://github.com/nbspou/switchboard
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  meta: ^1.1.5
  synchronized: ^1.5.3
  logging: ^0.11.3+2

dev_dependencies:
  test: ^1.0.0
  async: ^2.0.8
