name: wstalk
description: Library providing a natural interface to asynchronous network messaging by implementing a back-and-forth binary messaging protocol on top of WebSocket. 
version: 1.2.1
homepage: https://github.com/nbspou/wstalk
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  meta: ^1.1.5

dev_dependencies:
  test: ^1.0.0
